services:
  postgresql:
    image: postgres:15.2-alpine
    container_name: postgresql-stanza
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-db}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_PORT: 5432
    volumes:
      - ./apps/backend/database:/var/lib/postgresql/data

  python:
    build:
      context: ./apps/backend
      dockerfile: docker/Dockerfile
    container_name: python-service-stanza
    restart: unless-stopped
    ports:
      - "8678:8678"
    tty: true
    environment:
      languages: ["english"]
      use_gpu: false
      debug: true
      POSTGRES_DB: ${DB_DATABASE:-db}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_PORT: 5432
    volumes:
      - ./apps/backend/stanza-models:/app/stanza_resources
      - ./apps/backend/storage:/app/storage
